apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: finote-postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: finote-postgres
  template:
    metadata:
      labels:
        app: finote-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432

          envFrom:
            - secretRef:
                name: finote-postgres-secret

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 5
            periodSeconds: 5

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi