apiVersion: apps/v1
kind: Deployment
metadata:
  name: finote-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finote-backend
  template:
    metadata:
      labels:
        app: finote-backend
    spec:
      containers:
        - name: backend
          image: finote-backend-image
          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: finote-backend-config
            - secretRef:
                name: finote-postgres-secret

          env:
            - name: DATABASE_URL
              value: postgresql://finote_user:finote_password_renew@postgres:5432/finote
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: finote-backend-secret
                  key: SESSION_SECRET
                  
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
