resources:
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-ingress.yaml

images:
  - name: finote-frontend-image
    newName: ghcr.io/rakafde/fi_vps_noteapp_fe/finote-frontend
    newTag: 1.0.1-332643c
