apiVersion: batch/v1
kind: Job
metadata:
  name: finote-migrate
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: finote-backend-image
          command: ["npx", "drizzle-kit", "migrate", "--config=drizzle.config.ts"]

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: finote-backend-secret
                  key: DATABASE_URL

            - name: NODE_ENV
              value: production