name: Deploy Frontend

on:
  push:
    paths:
      - 'frontendss/**'
      - 'scripts/deploy_fe_k8s.sh'

jobs:
  deploy-frontend-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy Frontend
        uses: appleboy/ssh-action@v1.0.0
        env:
          GHCR_USER: rakafde
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          envs: GHCR_USER,GHCR_TOKEN
          script: |
            cd ~/finote/ops
            chmod +x scripts/deploy_fe_k8s.sh
            ./scripts/deploy_fe_k8s.sh